void amnesia(){
	
	char nomeFilme[4000] = "";
	char str1[150]="              #########################################################################################\n";
	char str2[150]="              #########################| S.A. Poster - Indicação de Filmes |###########################\n";
	char str3[150]="              #########################################################################################\n";
	char str4[150]="              _________________________________________________________________________________________\n";
	char str5[150]="              ###################################| Nome do Filme |#####################################\n";
	char str6[150]="              #########################################################################################\n";
	char str7[150]="              |                                                                                       |\n";
	char str8[150]="              |                                   Amnésia (Memento)                                   |\n";
	char str9[150]="              |_______________________________________________________________________________________|\n";
	char str10[150]="              ######################################| Sinopse |########################################\n";
	char str11[150]="              #########################################################################################\n";
	char str12[150]="              |                                                                                       |\n";
	char str13[150]="              |   Um homem possui um problema de perda de memória recente, impedindo-o de guardar     |\n";
	char str14[150]="              |   novos fatos. Através de anotações e tatuagens pelo seu corpo, ele tenta encontrar   |\n";
	char str15[150]="              |   e se vingar do homem que matou a sua mulher.                                        |\n";
	char str16[150]="              |_______________________________________________________________________________________|\n";
	char str17[150]="              ###########| Data de lançamento |#########|#########| Diretor & Roteirista(s) |##########\n";
	char str18[150]="              #########################################################################################\n";
	char str19[150]="              |                                         |                                             |\n";
	char str20[150]="              |         05 de Setembro de 2000          |              Christopher Nolan              |\n";
	char str21[150]="              |      31 de Agosto de 2001 (Brasil)      |                Jonathan Nolan               |\n";
	char str22[150]="              |_________________________________________|_____________________________________________|\n";
	char str23[150]="              #########| Informações Adicionais |#######|#########| Gênero(s) Secundário(s) |##########\n";
	char str24[150]="              #########################################################################################\n";
	char str25[150]="              |                                         |                                             |\n";
	char str26[150]="              |        Duração - 113 min (1h53min)      |                    Drama                    |\n";
	char str27[150]="              |      Classificação Etária - 16 anos     |                    Crime                    |\n";
	char str28[150]="              |_________________________________________|_____________________________________________|\n";
	char str29[150]="              ########| Nota no Rotten Tomatoes |#######|#########| Indicações e/ou Prêmios |##########\n";
	char str30[150]="              #########################################################################################\n";
	char str31[150]="              |                                         |                                             |\n";
	char str32[150]="              |        Nota dos Críticos - 8.2/10       | Melhor Roteiro Original - Oscar (Indicação) |\n";
	char str33[150]="              |        Nota da Audiência - 4.1/5        |      Melhor Edição - Oscar (Indicação)      |\n";
	char str34[150]="              |_________________________________________|_____________________________________________|\n";
	
	strncat (nomeFilme,str1,150);
	strncat (nomeFilme,str2,150);
	strncat (nomeFilme,str3,150);
	strncat (nomeFilme,str4,150);
	strncat (nomeFilme,str5,150);
	strncat (nomeFilme,str6,150);
	strncat (nomeFilme,str7,150);
	strncat (nomeFilme,str8,150);
	strncat (nomeFilme,str9,150);
	strncat (nomeFilme,str10,150);
	strncat (nomeFilme,str11,150);
	strncat (nomeFilme,str12,150);
	strncat (nomeFilme,str13,150);
	strncat (nomeFilme,str14,150);
	strncat (nomeFilme,str15,150);
	strncat (nomeFilme,str16,150);
	strncat (nomeFilme,str17,150);
	strncat (nomeFilme,str18,150);
	strncat (nomeFilme,str19,150);
	strncat (nomeFilme,str20,150);
	strncat (nomeFilme,str21,150);
	strncat (nomeFilme,str22,150);
	strncat (nomeFilme,str23,150);
	strncat (nomeFilme,str24,150);
	strncat (nomeFilme,str25,150);
	strncat (nomeFilme,str26,150);
	strncat (nomeFilme,str27,150);
	strncat (nomeFilme,str28,150);
	strncat (nomeFilme,str29,150);
	strncat (nomeFilme,str30,150);
	strncat (nomeFilme,str31,150);
	strncat (nomeFilme,str32,150);
	strncat (nomeFilme,str33,150);
	strncat (nomeFilme,str34,150);
		
	printf("%s",nomeFilme);
}
void cloverfield(){
	
	char nomeFilme[4000] = "";
	char str1[150]="              #########################################################################################\n";
	char str2[150]="              #########################| S.A. Poster - Indicação de Filmes |###########################\n";
	char str3[150]="              #########################################################################################\n";
	char str4[150]="              _________________________________________________________________________________________\n";
	char str5[150]="              ###################################| Nome do Filme |#####################################\n";
	char str6[150]="              #########################################################################################\n";
	char str7[150]="              |                                                                                       |\n";
	char str8[150]="              |                        Rua Cloverfield, 10 (10 Cloverfield Lane)                      |\n";
	char str9[150]="              |_______________________________________________________________________________________|\n";
	char str10[150]="              ######################################| Sinopse |########################################\n";
	char str11[150]="              #########################################################################################\n";
	char str12[150]="              |                                                                                       |\n";
	char str13[150]="              |   Uma jovem acorda presa em um porão subterrâneo e teme ser vítima de um sequestro.   |\n";
	char str14[150]="              |   Um homem explica que salvou a sua vida, mas não sabendo se pode confiar nele, ela   |\n";
	char str15[150]="              |   tenta se libertar o quanto antes.                                                   |\n";
	char str16[150]="              |_______________________________________________________________________________________|\n";
	char str17[150]="              ###########| Data de lançamento |#########|#########| Diretor & Roteirista(s) |##########\n";
	char str18[150]="              #########################################################################################\n";
	char str19[150]="              |                                         |                                             |\n";
	char str20[150]="              |           08 de Março de 2016           |              Dan Trachtenberg               |\n";
	char str21[150]="              |       07 de Abril de 2016 (Brasil)      |        Josh Campbell e Matt Stuecken        |\n";
	char str22[150]="              |_________________________________________|_____________________________________________|\n";
	char str23[150]="              #########| Informações Adicionais |#######|#########| Gênero(s) Secundário(s) |##########\n";
	char str24[150]="              #########################################################################################\n";
	char str25[150]="              |                                         |                                             |\n";
	char str26[150]="              |        Duração - 103 min (1h43min)      |                    Drama                    |\n";
	char str27[150]="              |      Classificação Etária - 14 anos     |              Ficção Científica              |\n";
	char str28[150]="              |_________________________________________|_____________________________________________|\n";
	char str29[150]="              ########| Nota no Rotten Tomatoes |#######|#########| Indicações e/ou Prêmios |##########\n";
	char str30[150]="              #########################################################################################\n";
	char str31[150]="              |                                         |                                             |\n";
	char str32[150]="              |        Nota dos Críticos - 7.5/10       |          Nenhum prêmio e/ou indicação       |\n";
	char str33[150]="              |        Nota da Audiência - 3.8/5        |                  importante                 |\n";
	char str34[150]="              |_________________________________________|_____________________________________________|\n";
	
	strncat (nomeFilme,str1,150);
	strncat (nomeFilme,str2,150);
	strncat (nomeFilme,str3,150);
	strncat (nomeFilme,str4,150);
	strncat (nomeFilme,str5,150);
	strncat (nomeFilme,str6,150);
	strncat (nomeFilme,str7,150);
	strncat (nomeFilme,str8,150);
	strncat (nomeFilme,str9,150);
	strncat (nomeFilme,str10,150);
	strncat (nomeFilme,str11,150);
	strncat (nomeFilme,str12,150);
	strncat (nomeFilme,str13,150);
	strncat (nomeFilme,str14,150);
	strncat (nomeFilme,str15,150);
	strncat (nomeFilme,str16,150);
	strncat (nomeFilme,str17,150);
	strncat (nomeFilme,str18,150);
	strncat (nomeFilme,str19,150);
	strncat (nomeFilme,str20,150);
	strncat (nomeFilme,str21,150);
	strncat (nomeFilme,str22,150);
	strncat (nomeFilme,str23,150);
	strncat (nomeFilme,str24,150);
	strncat (nomeFilme,str25,150);
	strncat (nomeFilme,str26,150);
	strncat (nomeFilme,str27,150);
	strncat (nomeFilme,str28,150);
	strncat (nomeFilme,str29,150);
	strncat (nomeFilme,str30,150);
	strncat (nomeFilme,str31,150);
	strncat (nomeFilme,str32,150);
	strncat (nomeFilme,str33,150);
	strncat (nomeFilme,str34,150);
		
	printf("%s",nomeFilme);
}
void paranoia(){
	
	char nomeFilme[4000] = "";
	char str1[150]="              #########################################################################################\n";
	char str2[150]="              #########################| S.A. Poster - Indicação de Filmes |###########################\n";
	char str3[150]="              #########################################################################################\n";
	char str4[150]="              _________________________________________________________________________________________\n";
	char str5[150]="              ###################################| Nome do Filme |#####################################\n";
	char str6[150]="              #########################################################################################\n";
	char str7[150]="              |                                                                                       |\n";
	char str8[150]="              |                                 Paranóia (Disturbia)                                  |\n";
	char str9[150]="              |_______________________________________________________________________________________|\n";
	char str10[150]="              ######################################| Sinopse |########################################\n";
	char str11[150]="              #########################################################################################\n";
	char str12[150]="              |                                                                                       |\n";
	char str13[150]="              |   Desde da morte de seu pai, um jovem anda bem triste e solitário. Ao ser colocado em |\n";
	char str14[150]="              |   prisão domiciliar, ele passa boa parte do tempo observando o comportamento estranho |\n";
	char str15[150]="              |   de seus vizinhos e começa a desconfiar que um deles seja um assassino em série.     |\n";
	char str16[150]="              |_______________________________________________________________________________________|\n";
	char str17[150]="              ###########| Data de lançamento |#########|#########| Diretor & Roteirista(s) |##########\n";
	char str18[150]="              #########################################################################################\n";
	char str19[150]="              |                                         |                                             |\n";
	char str20[150]="              |          13 de Abril de 2007            |                 D.J. Caruso                 |\n";
	char str21[150]="              |      31 de Agosto de 2007 (Brasil)      |      Christopher Landon e Carl Ellsworth    |\n";
	char str22[150]="              |_________________________________________|_____________________________________________|\n";
	char str23[150]="              #########| Informações Adicionais |#######|#########| Gênero(s) Secundário(s) |##########\n";
	char str24[150]="              #########################################################################################\n";
	char str25[150]="              |                                         |                                             |\n";
	char str26[150]="              |        Duração - 105 min (1h45min)      |                    Crime                    |\n";
	char str27[150]="              |      Classificação Etária - 14 anos     |                    Drama                    |\n";
	char str28[150]="              |_________________________________________|_____________________________________________|\n";
	char str29[150]="              ########| Nota no Rotten Tomatoes |#######|#########| Indicações e/ou Prêmios |##########\n";
	char str30[150]="              #########################################################################################\n";
	char str31[150]="              |                                         |                                             |\n";
	char str32[150]="              |        Nota dos Críticos - 6.2/10       |         Nenhum prêmio e/ou indicação        |\n";
	char str33[150]="              |        Nota da Audiência - 3.7/5        |                  importante                 |\n";
	char str34[150]="              |_________________________________________|_____________________________________________|\n";
	
	strncat (nomeFilme,str1,150);
	strncat (nomeFilme,str2,150);
	strncat (nomeFilme,str3,150);
	strncat (nomeFilme,str4,150);
	strncat (nomeFilme,str5,150);
	strncat (nomeFilme,str6,150);
	strncat (nomeFilme,str7,150);
	strncat (nomeFilme,str8,150);
	strncat (nomeFilme,str9,150);
	strncat (nomeFilme,str10,150);
	strncat (nomeFilme,str11,150);
	strncat (nomeFilme,str12,150);
	strncat (nomeFilme,str13,150);
	strncat (nomeFilme,str14,150);
	strncat (nomeFilme,str15,150);
	strncat (nomeFilme,str16,150);
	strncat (nomeFilme,str17,150);
	strncat (nomeFilme,str18,150);
	strncat (nomeFilme,str19,150);
	strncat (nomeFilme,str20,150);
	strncat (nomeFilme,str21,150);
	strncat (nomeFilme,str22,150);
	strncat (nomeFilme,str23,150);
	strncat (nomeFilme,str24,150);
	strncat (nomeFilme,str25,150);
	strncat (nomeFilme,str26,150);
	strncat (nomeFilme,str27,150);
	strncat (nomeFilme,str28,150);
	strncat (nomeFilme,str29,150);
	strncat (nomeFilme,str30,150);
	strncat (nomeFilme,str31,150);
	strncat (nomeFilme,str32,150);
	strncat (nomeFilme,str33,150);
	strncat (nomeFilme,str34,150);
		
	printf("%s",nomeFilme);
}
void numero(){
	
	char nomeFilme[4000] = "";
	char str1[150]="              #########################################################################################\n";
	char str2[150]="              #########################| S.A. Poster - Indicação de Filmes |###########################\n";
	char str3[150]="              #########################################################################################\n";
	char str4[150]="              _________________________________________________________________________________________\n";
	char str5[150]="              ###################################| Nome do Filme |#####################################\n";
	char str6[150]="              #########################################################################################\n";
	char str7[150]="              |                                                                                       |\n";
	char str8[150]="              |                               Número 23 (The Number 23)                               |\n";
	char str9[150]="              |_______________________________________________________________________________________|\n";
	char str10[150]="              ######################################| Sinopse |########################################\n";
	char str11[150]="              #########################################################################################\n";
	char str12[150]="              |                                                                                       |\n";
	char str13[150]="              |   Um homem encontra um livro obscuro sobre o número 23 e inicia uma jornada sombria.  |\n";
	char str14[150]="              |   À medida que ele se torna cada vez mais obcecado com o conteúdo, ele se convence de |\n";
	char str15[150]="              |   que o livro é baseado em sua vida.                                                  |\n";
	char str16[150]="              |_______________________________________________________________________________________|\n";
	char str17[150]="              ###########| Data de lançamento |#########|#########| Diretor & Roteirista(s) |##########\n";
	char str18[150]="              #########################################################################################\n";
	char str19[150]="              |                                         |                                             |\n";
	char str20[150]="              |         13 de Fevereiro de 2007         |               Joel Schumacher               |\n";
	char str21[150]="              |       23 de Março de 2007 (Brasil)      |               Fernley Phillips              |\n";
	char str22[150]="              |_________________________________________|_____________________________________________|\n";
	char str23[150]="              #########| Informações Adicionais |#######|#########| Gênero(s) Secundário(s) |##########\n";
	char str24[150]="              #########################################################################################\n";
	char str25[150]="              |                                         |                                             |\n";
	char str26[150]="              |        Duração - 98 min (1h38min)       |                    Crime                    |\n";
	char str27[150]="              |      Classificação Etária - 14 anos     |                   Mistério                  |\n";
	char str28[150]="              |_________________________________________|_____________________________________________|\n";
	char str29[150]="              ########| Nota no Rotten Tomatoes |#######|#########| Indicações e/ou Prêmios |##########\n";
	char str30[150]="              #########################################################################################\n";
	char str31[150]="              |                                         |                                             |\n";
	char str32[150]="              |        Nota dos Críticos - 3.5/10       |         Nenhum prêmio e/ou indicação        |\n";
	char str33[150]="              |        Nota da Audiência - 3.2/5        |                  importante                 |\n";
	char str34[150]="              |_________________________________________|_____________________________________________|\n";
	
	strncat (nomeFilme,str1,150);
	strncat (nomeFilme,str2,150);
	strncat (nomeFilme,str3,150);
	strncat (nomeFilme,str4,150);
	strncat (nomeFilme,str5,150);
	strncat (nomeFilme,str6,150);
	strncat (nomeFilme,str7,150);
	strncat (nomeFilme,str8,150);
	strncat (nomeFilme,str9,150);
	strncat (nomeFilme,str10,150);
	strncat (nomeFilme,str11,150);
	strncat (nomeFilme,str12,150);
	strncat (nomeFilme,str13,150);
	strncat (nomeFilme,str14,150);
	strncat (nomeFilme,str15,150);
	strncat (nomeFilme,str16,150);
	strncat (nomeFilme,str17,150);
	strncat (nomeFilme,str18,150);
	strncat (nomeFilme,str19,150);
	strncat (nomeFilme,str20,150);
	strncat (nomeFilme,str21,150);
	strncat (nomeFilme,str22,150);
	strncat (nomeFilme,str23,150);
	strncat (nomeFilme,str24,150);
	strncat (nomeFilme,str25,150);
	strncat (nomeFilme,str26,150);
	strncat (nomeFilme,str27,150);
	strncat (nomeFilme,str28,150);
	strncat (nomeFilme,str29,150);
	strncat (nomeFilme,str30,150);
	strncat (nomeFilme,str31,150);
	strncat (nomeFilme,str32,150);
	strncat (nomeFilme,str33,150);
	strncat (nomeFilme,str34,150);
		
	printf("%s",nomeFilme);
}
void lotr(){
	
	char nomeFilme[4000] = "";
	char str1[150]="              #########################################################################################\n";
	char str2[150]="              #########################| S.A. Poster - Indicação de Filmes |###########################\n";
	char str3[150]="              #########################################################################################\n";
	char str4[150]="              _________________________________________________________________________________________\n";
	char str5[150]="              ###################################| Nome do Filme |#####################################\n";
	char str6[150]="              #########################################################################################\n";
	char str7[150]="              |                                                                                       |\n";
	char str8[150]="              |       O Senhor dos Anéis: A Sociedade do Anel (LOTR: The Fellowship of the Ring)      |\n";
	char str9[150]="              |_______________________________________________________________________________________|\n";
	char str10[150]="              ######################################| Sinopse |########################################\n";
	char str11[150]="              #########################################################################################\n";
	char str12[150]="              |                                                                                       |\n";
	char str13[150]="              |   Um hobbit recebe de presente de seu tio um anel mágico e maligno que precisa ser    |\n";
	char str14[150]="              |   destruído antes que caia nas mãos do mal, pois o futuro da civilização depende do   |\n";
	char str15[150]="              |   destino desse anel.                                                                 |\n";
	char str16[150]="              |_______________________________________________________________________________________|\n";
	char str17[150]="              ###########| Data de lançamento |#########|#########| Diretor & Roteirista(s) |##########\n";
	char str18[150]="              #########################################################################################\n";
	char str19[150]="              |                                         |                                             |\n";
	char str20[150]="              |         19 de Dezembro de 2001          |                 Peter Jackson               |\n";
	char str21[150]="              |      01 de Janeiro de 2002 (Brasil)     |          Fran Walsh e Philippa Boyens       |\n";
	char str22[150]="              |_________________________________________|_____________________________________________|\n";
	char str23[150]="              #########| Informações Adicionais |#######|#########| Gênero(s) Secundário(s) |##########\n";
	char str24[150]="              #########################################################################################\n";
	char str25[150]="              |                                         |                                             |\n";
	char str26[150]="              |        Duração - 178 min (2h58min)      |                   Fantasia                  |\n";
	char str27[150]="              |      Classificação Etária - 12 anos     |                    Drama                    |\n";
	char str28[150]="              |_________________________________________|_____________________________________________|\n";
	char str29[150]="              ########| Nota no Rotten Tomatoes |#######|#########| Indicações e/ou Prêmios |##########\n";
	char str30[150]="              #########################################################################################\n";
	char str31[150]="              |                                         |                                             |\n";
	char str32[150]="              |        Nota dos Críticos - 8.2/10       |       Melhor Filme - BAFTA (Vencedor)       |\n";
	char str33[150]="              |        Nota da Audiência - 4.1/5        | Melhores Efeitos Visuais - Oscar (Vencedor) |\n";
	char str34[150]="              |_________________________________________|_____________________________________________|\n";
	
	strncat (nomeFilme,str1,150);
	strncat (nomeFilme,str2,150);
	strncat (nomeFilme,str3,150);
	strncat (nomeFilme,str4,150);
	strncat (nomeFilme,str5,150);
	strncat (nomeFilme,str6,150);
	strncat (nomeFilme,str7,150);
	strncat (nomeFilme,str8,150);
	strncat (nomeFilme,str9,150);
	strncat (nomeFilme,str10,150);
	strncat (nomeFilme,str11,150);
	strncat (nomeFilme,str12,150);
	strncat (nomeFilme,str13,150);
	strncat (nomeFilme,str14,150);
	strncat (nomeFilme,str15,150);
	strncat (nomeFilme,str16,150);
	strncat (nomeFilme,str17,150);
	strncat (nomeFilme,str18,150);
	strncat (nomeFilme,str19,150);
	strncat (nomeFilme,str20,150);
	strncat (nomeFilme,str21,150);
	strncat (nomeFilme,str22,150);
	strncat (nomeFilme,str23,150);
	strncat (nomeFilme,str24,150);
	strncat (nomeFilme,str25,150);
	strncat (nomeFilme,str26,150);
	strncat (nomeFilme,str27,150);
	strncat (nomeFilme,str28,150);
	strncat (nomeFilme,str29,150);
	strncat (nomeFilme,str30,150);
	strncat (nomeFilme,str31,150);
	strncat (nomeFilme,str32,150);
	strncat (nomeFilme,str33,150);
	strncat (nomeFilme,str34,150);
		
	printf("%s",nomeFilme);
}
void limiteAmanha(){
	
	char nomeFilme[4000] = "";
	char str1[150]="              #########################################################################################\n";
	char str2[150]="              #########################| S.A. Poster - Indicação de Filmes |###########################\n";
	char str3[150]="              #########################################################################################\n";
	char str4[150]="              _________________________________________________________________________________________\n";
	char str5[150]="              ###################################| Nome do Filme |#####################################\n";
	char str6[150]="              #########################################################################################\n";
	char str7[150]="              |                                                                                       |\n";
	char str8[150]="              |                          No Limite do Amanhã (Edge of Tomorrow)                       |\n";
	char str9[150]="              |_______________________________________________________________________________________|\n";
	char str10[150]="              ######################################| Sinopse |########################################\n";
	char str11[150]="              #########################################################################################\n";
	char str12[150]="              |                                                                                       |\n";
	char str13[150]="              |  Quando a Terra é tomada por alienígenas, um soldado é obrigado a juntar-se às Forças |\n";
	char str14[150]="              |  Armadas e ir para a linha de frente no dia do confronto final. Inexplicavelmente ele |\n";
	char str15[150]="              |  acaba preso no tempo, condenado a reviver esta data repetidamente.                   |\n";
	char str16[150]="              |_______________________________________________________________________________________|\n";
	char str17[150]="              ###########| Data de lançamento |#########|#########| Diretor & Roteirista(s) |##########\n";
	char str18[150]="              #########################################################################################\n";
	char str19[150]="              |                                         |                                             |\n";
	char str20[150]="              |           28 de Maio de 2014            |                Doug Liman                   |\n";
	char str21[150]="              |       29 de Maio de 2014 (Brasil)       |   Christopher McQuarrie e Jez Butterworth   |\n";
	char str22[150]="              |_________________________________________|_____________________________________________|\n";
	char str23[150]="              #########| Informações Adicionais |#######|#########| Gênero(s) Secundário(s) |##########\n";
	char str24[150]="              #########################################################################################\n";
	char str25[150]="              |                                         |                                             |\n";
	char str26[150]="              |        Duração - 113 min (1h53min)      |              Ficção Científica              |\n";
	char str27[150]="              |      Classificação Etária - 14 anos     |                                             |\n";
	char str28[150]="              |_________________________________________|_____________________________________________|\n";
	char str29[150]="              ########| Nota no Rotten Tomatoes |#######|#########| Indicações e/ou Prêmios |##########\n";
	char str30[150]="              #########################################################################################\n";
	char str31[150]="              |                                         |                                             |\n";
	char str32[150]="              |        Nota dos Críticos - 7.5/10       |         Nenhum prêmio e/ou indicação        |\n";
	char str33[150]="              |        Nota da Audiência - 4.2/5        |                  importante                 |\n";
	char str34[150]="              |_________________________________________|_____________________________________________|\n";
	
	strncat (nomeFilme,str1,150);
	strncat (nomeFilme,str2,150);
	strncat (nomeFilme,str3,150);
	strncat (nomeFilme,str4,150);
	strncat (nomeFilme,str5,150);
	strncat (nomeFilme,str6,150);
	strncat (nomeFilme,str7,150);
	strncat (nomeFilme,str8,150);
	strncat (nomeFilme,str9,150);
	strncat (nomeFilme,str10,150);
	strncat (nomeFilme,str11,150);
	strncat (nomeFilme,str12,150);
	strncat (nomeFilme,str13,150);
	strncat (nomeFilme,str14,150);
	strncat (nomeFilme,str15,150);
	strncat (nomeFilme,str16,150);
	strncat (nomeFilme,str17,150);
	strncat (nomeFilme,str18,150);
	strncat (nomeFilme,str19,150);
	strncat (nomeFilme,str20,150);
	strncat (nomeFilme,str21,150);
	strncat (nomeFilme,str22,150);
	strncat (nomeFilme,str23,150);
	strncat (nomeFilme,str24,150);
	strncat (nomeFilme,str25,150);
	strncat (nomeFilme,str26,150);
	strncat (nomeFilme,str27,150);
	strncat (nomeFilme,str28,150);
	strncat (nomeFilme,str29,150);
	strncat (nomeFilme,str30,150);
	strncat (nomeFilme,str31,150);
	strncat (nomeFilme,str32,150);
	strncat (nomeFilme,str33,150);
	strncat (nomeFilme,str34,150);
		
	printf("%s",nomeFilme);
}
void lucy(){
	
	char nomeFilme[4000] = "";
	char str1[150]="              #########################################################################################\n";
	char str2[150]="              #########################| S.A. Poster - Indicação de Filmes |###########################\n";
	char str3[150]="              #########################################################################################\n";
	char str4[150]="              _________________________________________________________________________________________\n";
	char str5[150]="              ###################################| Nome do Filme |#####################################\n";
	char str6[150]="              #########################################################################################\n";
	char str7[150]="              |                                                                                       |\n";
	char str8[150]="              |                                         Lucy                                          |\n";
	char str9[150]="              |_______________________________________________________________________________________|\n";
	char str10[150]="              ######################################| Sinopse |########################################\n";
	char str11[150]="              #########################################################################################\n";
	char str12[150]="              |                                                                                       |\n";
	char str13[150]="              |   Lucy é obrigada a contrabandear drogas dentro do estômago. Mas o corpo da jovem     |\n";
	char str14[150]="              |   absorve as substâncias e ela passa a ter superpoderes, como telepatia, telecinesia, |\n";
	char str15[150]="              |   a ausência de dor e a capacidade de adquirir conhecimento instantaneamente.         |\n";
	char str16[150]="              |_______________________________________________________________________________________|\n";
	char str17[150]="              ###########| Data de lançamento |#########|#########| Diretor & Roteirista(s) |##########\n";
	char str18[150]="              #########################################################################################\n";
	char str19[150]="              |                                         |                                             |\n";
	char str20[150]="              |           25 de Julho de 2014           |                Luc Besson                   |\n";
	char str21[150]="              |       28 de Augusto de 2014 (Brasil)    |                                             |\n";
	char str22[150]="              |_________________________________________|_____________________________________________|\n";
	char str23[150]="              #########| Informações Adicionais |#######|#########| Gênero(s) Secundário(s) |##########\n";
	char str24[150]="              #########################################################################################\n";
	char str25[150]="              |                                         |                                             |\n";
	char str26[150]="              |        Duração - 89 min (1h29min)       |              Ficção Científica              |\n";
	char str27[150]="              |      Classificação Etária - 16 anos     |                   Aventura                  |\n";
	char str28[150]="              |_________________________________________|_____________________________________________|\n";
	char str29[150]="              ########| Nota no Rotten Tomatoes |#######|#########| Indicações e/ou Prêmios |##########\n";
	char str30[150]="              #########################################################################################\n";
	char str31[150]="              |                                         |                                             |\n";
	char str32[150]="              |        Nota dos Críticos - 6/10         |         Nenhum prêmio e/ou indicação        |\n";
	char str33[150]="              |        Nota da Audiência - 3.2/5        |                  importante                 |\n";
	char str34[150]="              |_________________________________________|_____________________________________________|\n";
	
	strncat (nomeFilme,str1,150);
	strncat (nomeFilme,str2,150);
	strncat (nomeFilme,str3,150);
	strncat (nomeFilme,str4,150);
	strncat (nomeFilme,str5,150);
	strncat (nomeFilme,str6,150);
	strncat (nomeFilme,str7,150);
	strncat (nomeFilme,str8,150);
	strncat (nomeFilme,str9,150);
	strncat (nomeFilme,str10,150);
	strncat (nomeFilme,str11,150);
	strncat (nomeFilme,str12,150);
	strncat (nomeFilme,str13,150);
	strncat (nomeFilme,str14,150);
	strncat (nomeFilme,str15,150);
	strncat (nomeFilme,str16,150);
	strncat (nomeFilme,str17,150);
	strncat (nomeFilme,str18,150);
	strncat (nomeFilme,str19,150);
	strncat (nomeFilme,str20,150);
	strncat (nomeFilme,str21,150);
	strncat (nomeFilme,str22,150);
	strncat (nomeFilme,str23,150);
	strncat (nomeFilme,str24,150);
	strncat (nomeFilme,str25,150);
	strncat (nomeFilme,str26,150);
	strncat (nomeFilme,str27,150);
	strncat (nomeFilme,str28,150);
	strncat (nomeFilme,str29,150);
	strncat (nomeFilme,str30,150);
	strncat (nomeFilme,str31,150);
	strncat (nomeFilme,str32,150);
	strncat (nomeFilme,str33,150);
	strncat (nomeFilme,str34,150);
		
	printf("%s",nomeFilme);
}
void jumper(){
	
	char nomeFilme[4000] = "";
	char str1[150]="              #########################################################################################\n";
	char str2[150]="              #########################| S.A. Poster - Indicação de Filmes |###########################\n";
	char str3[150]="              #########################################################################################\n";
	char str4[150]="              _________________________________________________________________________________________\n";
	char str5[150]="              ###################################| Nome do Filme |#####################################\n";
	char str6[150]="              #########################################################################################\n";
	char str7[150]="              |                                                                                       |\n";
	char str8[150]="              |                                        Jumper                                         |\n";
	char str9[150]="              |_______________________________________________________________________________________|\n";
	char str10[150]="              ######################################| Sinopse |########################################\n";
	char str11[150]="              #########################################################################################\n";
	char str12[150]="              |                                                                                       |\n";
	char str13[150]="              |   Um adolescente com habilidades de teletransporte de repente encontra-se no meio     |\n";
	char str14[150]="              |   de uma antiga guerra entre aqueles como ele e seus aniquiladores juramentados.      |\n";
	char str15[150]="              |                                                                                       |\n";
	char str16[150]="              |_______________________________________________________________________________________|\n";
	char str17[150]="              ###########| Data de lançamento |#########|#########| Diretor & Roteirista(s) |##########\n";
	char str18[150]="              #########################################################################################\n";
	char str19[150]="              |                                         |                                             |\n";
	char str20[150]="              |          11 de Fevereiro de 2008        |                Doug Liman                   |\n";
	char str21[150]="              |       28 de Março de 2008 (Brasil)      |         David S. Goyer e Jim Uhls           |\n";
	char str22[150]="              |_________________________________________|_____________________________________________|\n";
	char str23[150]="              #########| Informações Adicionais |#######|#########| Gênero(s) Secundário(s) |##########\n";
	char str24[150]="              #########################################################################################\n";
	char str25[150]="              |                                         |                                             |\n";
	char str26[150]="              |        Duração - 88 min (1h28min)       |              Ficção Científica              |\n";
	char str27[150]="              |      Classificação Etária - 12 anos     |                    Ação                     |\n";
	char str28[150]="              |_________________________________________|_____________________________________________|\n";
	char str29[150]="              ########| Nota no Rotten Tomatoes |#######|#########| Indicações e/ou Prêmios |##########\n";
	char str30[150]="              #########################################################################################\n";
	char str31[150]="              |                                         |                                             |\n";
	char str32[150]="              |        Nota dos Críticos - 4/10         |         Nenhum prêmio e/ou indicação        |\n";
	char str33[150]="              |        Nota da Audiência - 3.1/5        |                  importante                 |\n";
	char str34[150]="              |_________________________________________|_____________________________________________|\n";
	
	strncat (nomeFilme,str1,150);
	strncat (nomeFilme,str2,150);
	strncat (nomeFilme,str3,150);
	strncat (nomeFilme,str4,150);
	strncat (nomeFilme,str5,150);
	strncat (nomeFilme,str6,150);
	strncat (nomeFilme,str7,150);
	strncat (nomeFilme,str8,150);
	strncat (nomeFilme,str9,150);
	strncat (nomeFilme,str10,150);
	strncat (nomeFilme,str11,150);
	strncat (nomeFilme,str12,150);
	strncat (nomeFilme,str13,150);
	strncat (nomeFilme,str14,150);
	strncat (nomeFilme,str15,150);
	strncat (nomeFilme,str16,150);
	strncat (nomeFilme,str17,150);
	strncat (nomeFilme,str18,150);
	strncat (nomeFilme,str19,150);
	strncat (nomeFilme,str20,150);
	strncat (nomeFilme,str21,150);
	strncat (nomeFilme,str22,150);
	strncat (nomeFilme,str23,150);
	strncat (nomeFilme,str24,150);
	strncat (nomeFilme,str25,150);
	strncat (nomeFilme,str26,150);
	strncat (nomeFilme,str27,150);
	strncat (nomeFilme,str28,150);
	strncat (nomeFilme,str29,150);
	strncat (nomeFilme,str30,150);
	strncat (nomeFilme,str31,150);
	strncat (nomeFilme,str32,150);
	strncat (nomeFilme,str33,150);
	strncat (nomeFilme,str34,150);
		
	printf("%s",nomeFilme);
}
void theGodfather(){
	
	char nomeFilme[4000] = "";
	char str1[150]="              #########################################################################################\n";
	char str2[150]="              #########################| S.A. Poster - Indicação de Filmes |###########################\n";
	char str3[150]="              #########################################################################################\n";
	char str4[150]="              _________________________________________________________________________________________\n";
	char str5[150]="              ###################################| Nome do Filme |#####################################\n";
	char str6[150]="              #########################################################################################\n";
	char str7[150]="              |                                                                                       |\n";
	char str8[150]="              |                             O Poderoso Chefão (The Godfather)                         |\n";
	char str9[150]="              |_______________________________________________________________________________________|\n";
	char str10[150]="              ######################################| Sinopse |########################################\n";
	char str11[150]="              #########################################################################################\n";
	char str12[150]="              |                                                                                       |\n";
	char str13[150]="              |  A saga conta a história de uma família mafiosa que luta para estabelecer sua         |\n";
	char str14[150]="              |  supremacia na América depois da Segunda Guerra. Uma tentativa de assassinato deixa   |\n";
	char str15[150]="              |  Vito Corleone incapacitado e força os filhos Michael e Sonny a assumirem os negócios.|\n";
	char str16[150]="              |_______________________________________________________________________________________|\n";
	char str17[150]="              ###########| Data de lançamento |#########|#########| Diretor & Roteirista(s) |##########\n";
	char str18[150]="              #########################################################################################\n";
	char str19[150]="              |                                         |                                             |\n";
	char str20[150]="              |           14 de Março de 1972           |             Francis Ford Coppola            |\n";
	char str21[150]="              |       10 de Setembro de 1972 (Brasil)   |         Francis F. Coppola e Mario Puzo     |\n";
	char str22[150]="              |_________________________________________|_____________________________________________|\n";
	char str23[150]="              #########| Informações Adicionais |#######|#########| Gênero(s) Secundário(s) |##########\n";
	char str24[150]="              #########################################################################################\n";
	char str25[150]="              |                                         |                                             |\n";
	char str26[150]="              |        Duração - 175 min (2h55min)      |                    Crime                    |\n";
	char str27[150]="              |      Classificação Etária - 14 anos     |                                             |\n";
	char str28[150]="              |_________________________________________|_____________________________________________|\n";
	char str29[150]="              ########| Nota no Rotten Tomatoes |#######|#########| Indicações e/ou Prêmios |##########\n";
	char str30[150]="              #########################################################################################\n";
	char str31[150]="              |                                         |                                             |\n";
	char str32[150]="              |        Nota dos Críticos - 9.3/10       |  Melhor roteiro adaptado - Oscar (Vencedor) |\n";
	char str33[150]="              |        Nota da Audiência - 4.4/5        |                                             |\n";
	char str34[150]="              |_________________________________________|_____________________________________________|\n";
	
	strncat (nomeFilme,str1,150);
	strncat (nomeFilme,str2,150);
	strncat (nomeFilme,str3,150);
	strncat (nomeFilme,str4,150);
	strncat (nomeFilme,str5,150);
	strncat (nomeFilme,str6,150);
	strncat (nomeFilme,str7,150);
	strncat (nomeFilme,str8,150);
	strncat (nomeFilme,str9,150);
	strncat (nomeFilme,str10,150);
	strncat (nomeFilme,str11,150);
	strncat (nomeFilme,str12,150);
	strncat (nomeFilme,str13,150);
	strncat (nomeFilme,str14,150);
	strncat (nomeFilme,str15,150);
	strncat (nomeFilme,str16,150);
	strncat (nomeFilme,str17,150);
	strncat (nomeFilme,str18,150);
	strncat (nomeFilme,str19,150);
	strncat (nomeFilme,str20,150);
	strncat (nomeFilme,str21,150);
	strncat (nomeFilme,str22,150);
	strncat (nomeFilme,str23,150);
	strncat (nomeFilme,str24,150);
	strncat (nomeFilme,str25,150);
	strncat (nomeFilme,str26,150);
	strncat (nomeFilme,str27,150);
	strncat (nomeFilme,str28,150);
	strncat (nomeFilme,str29,150);
	strncat (nomeFilme,str30,150);
	strncat (nomeFilme,str31,150);
	strncat (nomeFilme,str32,150);
	strncat (nomeFilme,str33,150);
	strncat (nomeFilme,str34,150);
		
	printf("%s",nomeFilme);
}
void abutre(){
	
	char nomeFilme[4000] = "";
	char str1[150]="              #########################################################################################\n";
	char str2[150]="              #########################| S.A. Poster - Indicação de Filmes |###########################\n";
	char str3[150]="              #########################################################################################\n";
	char str4[150]="              _________________________________________________________________________________________\n";
	char str5[150]="              ###################################| Nome do Filme |#####################################\n";
	char str6[150]="              #########################################################################################\n";
	char str7[150]="              |                                                                                       |\n";
	char str8[150]="              |                                O Abutre (Nightcrawler)                                |\n";
	char str9[150]="              |_______________________________________________________________________________________|\n";
	char str10[150]="              ######################################| Sinopse |########################################\n";
	char str11[150]="              #########################################################################################\n";
	char str12[150]="              |                                                                                       |\n";
	char str13[150]="              |   Para enfrentar dificuldades de conseguir um emprego formal, um jovem decide entrar  |\n";
	char str14[150]="              |   no agitado submundo do jornalismo criminal independente de Los Angeles.             |\n";
	char str15[150]="              |                                                                                       |\n";
	char str16[150]="              |_______________________________________________________________________________________|\n";
	char str17[150]="              ###########| Data de lançamento |#########|#########| Diretor & Roteirista(s) |##########\n";
	char str18[150]="              #########################################################################################\n";
	char str19[150]="              |                                         |                                             |\n";
	char str20[150]="              |          05 de Setembro de 2014         |                 Dan Gilroy                  |\n";
	char str21[150]="              |       18 de Dezembro de 2014 (Brasil)   |                                             |\n";
	char str22[150]="              |_________________________________________|_____________________________________________|\n";
	char str23[150]="              #########| Informações Adicionais |#######|#########| Gênero(s) Secundário(s) |##########\n";
	char str24[150]="              #########################################################################################\n";
	char str25[150]="              |                                         |                                             |\n";
	char str26[150]="              |        Duração - 117 min (1h57min)      |                    Crime                    |\n";
	char str27[150]="              |      Classificação Etária - 14 anos     |                   Suspense                  |\n";
	char str28[150]="              |_________________________________________|_____________________________________________|\n";
	char str29[150]="              ########| Nota no Rotten Tomatoes |#######|#########| Indicações e/ou Prêmios |##########\n";
	char str30[150]="              #########################################################################################\n";
	char str31[150]="              |                                         |                                             |\n";
	char str32[150]="              |        Nota dos Críticos - 8.2/10       | Melhor roteiro original - Oscar (Indicação) |\n";
	char str33[150]="              |         Nota da Audiência - 4/5         |                                             |\n";
	char str34[150]="              |_________________________________________|_____________________________________________|\n";
	
	strncat (nomeFilme,str1,150);
	strncat (nomeFilme,str2,150);
	strncat (nomeFilme,str3,150);
	strncat (nomeFilme,str4,150);
	strncat (nomeFilme,str5,150);
	strncat (nomeFilme,str6,150);
	strncat (nomeFilme,str7,150);
	strncat (nomeFilme,str8,150);
	strncat (nomeFilme,str9,150);
	strncat (nomeFilme,str10,150);
	strncat (nomeFilme,str11,150);
	strncat (nomeFilme,str12,150);
	strncat (nomeFilme,str13,150);
	strncat (nomeFilme,str14,150);
	strncat (nomeFilme,str15,150);
	strncat (nomeFilme,str16,150);
	strncat (nomeFilme,str17,150);
	strncat (nomeFilme,str18,150);
	strncat (nomeFilme,str19,150);
	strncat (nomeFilme,str20,150);
	strncat (nomeFilme,str21,150);
	strncat (nomeFilme,str22,150);
	strncat (nomeFilme,str23,150);
	strncat (nomeFilme,str24,150);
	strncat (nomeFilme,str25,150);
	strncat (nomeFilme,str26,150);
	strncat (nomeFilme,str27,150);
	strncat (nomeFilme,str28,150);
	strncat (nomeFilme,str29,150);
	strncat (nomeFilme,str30,150);
	strncat (nomeFilme,str31,150);
	strncat (nomeFilme,str32,150);
	strncat (nomeFilme,str33,150);
	strncat (nomeFilme,str34,150);
		
	printf("%s",nomeFilme);
}
void kevin(){
	
	char nomeFilme[4000] = "";
	char str1[150]="              #########################################################################################\n";
	char str2[150]="              #########################| S.A. Poster - Indicação de Filmes |###########################\n";
	char str3[150]="              #########################################################################################\n";
	char str4[150]="              _________________________________________________________________________________________\n";
	char str5[150]="              ###################################| Nome do Filme |#####################################\n";
	char str6[150]="              #########################################################################################\n";
	char str7[150]="              |                                                                                       |\n";
	char str8[150]="              |               Precisamos falar sobre Kevin (We need to talk about Kevin)              |\n";
	char str9[150]="              |_______________________________________________________________________________________|\n";
	char str10[150]="              ######################################| Sinopse |########################################\n";
	char str11[150]="              #########################################################################################\n";
	char str12[150]="              |                                                                                       |\n";
	char str13[150]="              |  Eva (Tilda Swinton) nunca quis ser mãe e por isso tem uma relação complicada com seu |\n";
	char str14[150]="              |  filho Kevin. Agora, o adolescente está preso por ter sido o responsável por uma      |\n";
	char str15[150]="              |  tragédia, e Eva tenta lidar com a sensação de responsabilidade pelo que aconteceu.   |\n";
	char str16[150]="              |_______________________________________________________________________________________|\n";
	char str17[150]="              ###########| Data de lançamento |#########|#########| Diretor & Roteirista(s) |##########\n";
	char str18[150]="              #########################################################################################\n";
	char str19[150]="              |                                         |                                             |\n";
	char str20[150]="              |           12 de Maio de 2011            |                Lynne Ramsay                 |\n";
	char str21[150]="              |       06 de Outubro de 2011 (Brasil)    |       Lynne Ramsay e Rory Stewart Kinnear   |\n";
	char str22[150]="              |_________________________________________|_____________________________________________|\n";
	char str23[150]="              #########| Informações Adicionais |#######|#########| Gênero(s) Secundário(s) |##########\n";
	char str24[150]="              #########################################################################################\n";
	char str25[150]="              |                                         |                                             |\n";
	char str26[150]="              |        Duração - 112 min (1h52min)      |                   Mistério                  |\n";
	char str27[150]="              |      Classificação Etária - 16 anos     |                   Suspense                  |\n";
	char str28[150]="              |_________________________________________|_____________________________________________|\n";
	char str29[150]="              ########| Nota no Rotten Tomatoes |#######|#########| Indicações e/ou Prêmios |##########\n";
	char str30[150]="              #########################################################################################\n";
	char str31[150]="              |                                         |                                             |\n";
	char str32[150]="              |        Nota dos Críticos - 7.4/10       |         Nenhum prêmio e/ou indicação        |\n";
	char str33[150]="              |         Nota da Audiência - 3.8/5       |                  importante                 |\n";
	char str34[150]="              |_________________________________________|_____________________________________________|\n";
	
	strncat (nomeFilme,str1,150);
	strncat (nomeFilme,str2,150);
	strncat (nomeFilme,str3,150);
	strncat (nomeFilme,str4,150);
	strncat (nomeFilme,str5,150);
	strncat (nomeFilme,str6,150);
	strncat (nomeFilme,str7,150);
	strncat (nomeFilme,str8,150);
	strncat (nomeFilme,str9,150);
	strncat (nomeFilme,str10,150);
	strncat (nomeFilme,str11,150);
	strncat (nomeFilme,str12,150);
	strncat (nomeFilme,str13,150);
	strncat (nomeFilme,str14,150);
	strncat (nomeFilme,str15,150);
	strncat (nomeFilme,str16,150);
	strncat (nomeFilme,str17,150);
	strncat (nomeFilme,str18,150);
	strncat (nomeFilme,str19,150);
	strncat (nomeFilme,str20,150);
	strncat (nomeFilme,str21,150);
	strncat (nomeFilme,str22,150);
	strncat (nomeFilme,str23,150);
	strncat (nomeFilme,str24,150);
	strncat (nomeFilme,str25,150);
	strncat (nomeFilme,str26,150);
	strncat (nomeFilme,str27,150);
	strncat (nomeFilme,str28,150);
	strncat (nomeFilme,str29,150);
	strncat (nomeFilme,str30,150);
	strncat (nomeFilme,str31,150);
	strncat (nomeFilme,str32,150);
	strncat (nomeFilme,str33,150);
	strncat (nomeFilme,str34,150);
		
	printf("%s",nomeFilme);
}
void cidadeSonhos(){
	
	char nomeFilme[4000] = "";
	char str1[150]="              #########################################################################################\n";
	char str2[150]="              #########################| S.A. Poster - Indicação de Filmes |###########################\n";
	char str3[150]="              #########################################################################################\n";
	char str4[150]="              _________________________________________________________________________________________\n";
	char str5[150]="              ###################################| Nome do Filme |#####################################\n";
	char str6[150]="              #########################################################################################\n";
	char str7[150]="              |                                                                                       |\n";
	char str8[150]="              |                          Cidade dos Sonhos (Mulholland Drive)                         |\n";
	char str9[150]="              |_______________________________________________________________________________________|\n";
	char str10[150]="              ######################################| Sinopse |########################################\n";
	char str11[150]="              #########################################################################################\n";
	char str12[150]="              |                                                                                       |\n";
	char str13[150]="              |  Uma jovem atriz viaja para Hollywood e se vê emaranhada numa intriga secreta com     |\n";
	char str14[150]="              |  uma mulher que escapou por pouco de ser assassinada, e que agora se encontra com     |\n";
	char str15[150]="              |  amnésia devido a um acidente de carro. Seu mundo se torna um pesadelo e surreal.     |\n";
	char str16[150]="              |_______________________________________________________________________________________|\n";
	char str17[150]="              ###########| Data de lançamento |#########|#########| Diretor & Roteirista(s) |##########\n";
	char str18[150]="              #########################################################################################\n";
	char str19[150]="              |                                         |                                             |\n";
	char str20[150]="              |           16 de Maio de 2001            |                David Lynch                  |\n";
	char str21[150]="              |        21 de Junho de 2002 (Brasil)     |                                             |\n";
	char str22[150]="              |_________________________________________|_____________________________________________|\n";
	char str23[150]="              #########| Informações Adicionais |#######|#########| Gênero(s) Secundário(s) |##########\n";
	char str24[150]="              #########################################################################################\n";
	char str25[150]="              |                                         |                                             |\n";
	char str26[150]="              |        Duração - 147 min (2h27min)      |                   Mistério                  |\n";
	char str27[150]="              |      Classificação Etária - 16 anos     |                   Suspense                  |\n";
	char str28[150]="              |_________________________________________|_____________________________________________|\n";
	char str29[150]="              ########| Nota no Rotten Tomatoes |#######|#########| Indicações e/ou Prêmios |##########\n";
	char str30[150]="              #########################################################################################\n";
	char str31[150]="              |                                         |                                             |\n";
	char str32[150]="              |        Nota dos Críticos - 7.6/10       |   Melhor Filme - Globo de Ouro (Indicação)  |\n";
	char str33[150]="              |         Nota da Audiência - 3.7/5       |       Melhor Edição - BAFTA (Vencedor)      |\n";
	char str34[150]="              |_________________________________________|_____________________________________________|\n";
	
	strncat (nomeFilme,str1,150);
	strncat (nomeFilme,str2,150);
	strncat (nomeFilme,str3,150);
	strncat (nomeFilme,str4,150);
	strncat (nomeFilme,str5,150);
	strncat (nomeFilme,str6,150);
	strncat (nomeFilme,str7,150);
	strncat (nomeFilme,str8,150);
	strncat (nomeFilme,str9,150);
	strncat (nomeFilme,str10,150);
	strncat (nomeFilme,str11,150);
	strncat (nomeFilme,str12,150);
	strncat (nomeFilme,str13,150);
	strncat (nomeFilme,str14,150);
	strncat (nomeFilme,str15,150);
	strncat (nomeFilme,str16,150);
	strncat (nomeFilme,str17,150);
	strncat (nomeFilme,str18,150);
	strncat (nomeFilme,str19,150);
	strncat (nomeFilme,str20,150);
	strncat (nomeFilme,str21,150);
	strncat (nomeFilme,str22,150);
	strncat (nomeFilme,str23,150);
	strncat (nomeFilme,str24,150);
	strncat (nomeFilme,str25,150);
	strncat (nomeFilme,str26,150);
	strncat (nomeFilme,str27,150);
	strncat (nomeFilme,str28,150);
	strncat (nomeFilme,str29,150);
	strncat (nomeFilme,str30,150);
	strncat (nomeFilme,str31,150);
	strncat (nomeFilme,str32,150);
	strncat (nomeFilme,str33,150);
	strncat (nomeFilme,str34,150);
		
	printf("%s",nomeFilme);
}
void dozeMacacos(){
	
	char nomeFilme[4000] = "";
	char str1[150]="              #########################################################################################\n";
	char str2[150]="              #########################| S.A. Poster - Indicação de Filmes |###########################\n";
	char str3[150]="              #########################################################################################\n";
	char str4[150]="              _________________________________________________________________________________________\n";
	char str5[150]="              ###################################| Nome do Filme |#####################################\n";
	char str6[150]="              #########################################################################################\n";
	char str7[150]="              |                                                                                       |\n";
	char str8[150]="              |                                12 Macacos (12 Monkeys)                                |\n";
	char str9[150]="              |_______________________________________________________________________________________|\n";
	char str10[150]="              ######################################| Sinopse |########################################\n";
	char str11[150]="              #########################################################################################\n";
	char str12[150]="              |                                                                                       |\n";
	char str13[150]="              | Um condenado do ano de 2035 é enviado de volta no tempo para descobrir a causa de um  |\n";
	char str14[150]="              | vírus que acabou com quase toda a população do planeta. Os poucos sobreviventes moram |\n";
	char str15[150]="              | em abrigos subterrâneos.                                                              |\n";
	char str16[150]="              |_______________________________________________________________________________________|\n";
	char str17[150]="              ###########| Data de lançamento |#########|#########| Diretor & Roteirista(s) |##########\n";
	char str18[150]="              #########################################################################################\n";
	char str19[150]="              |                                         |                                             |\n";
	char str20[150]="              |           08 de Dezembro de 1995        |                Terry Gilliam                |\n";
	char str21[150]="              |        22 de Março de 1996 (Brasil)     |            David e Janet Peoples            |\n";
	char str22[150]="              |_________________________________________|_____________________________________________|\n";
	char str23[150]="              #########| Informações Adicionais |#######|#########| Gênero(s) Secundário(s) |##########\n";
	char str24[150]="              #########################################################################################\n";
	char str25[150]="              |                                         |                                             |\n";
	char str26[150]="              |        Duração - 129 min (2h09min)      |                   Mistério                  |\n";
	char str27[150]="              |      Classificação Etária - 14 anos     |                   Suspense                  |\n";
	char str28[150]="              |_________________________________________|_____________________________________________|\n";
	char str29[150]="              ########| Nota no Rotten Tomatoes |#######|#########| Indicações e/ou Prêmios |##########\n";
	char str30[150]="              #########################################################################################\n";
	char str31[150]="              |                                         |                                             |\n";
	char str32[150]="              |        Nota dos Críticos - 7.5/10       |         Nenhum prêmio e/ou indicação        |\n";
	char str33[150]="              |         Nota da Audiência - 3.7/5       |                  importante                 |\n";
	char str34[150]="              |_________________________________________|_____________________________________________|\n";
	
	strncat (nomeFilme,str1,150);
	strncat (nomeFilme,str2,150);
	strncat (nomeFilme,str3,150);
	strncat (nomeFilme,str4,150);
	strncat (nomeFilme,str5,150);
	strncat (nomeFilme,str6,150);
	strncat (nomeFilme,str7,150);
	strncat (nomeFilme,str8,150);
	strncat (nomeFilme,str9,150);
	strncat (nomeFilme,str10,150);
	strncat (nomeFilme,str11,150);
	strncat (nomeFilme,str12,150);
	strncat (nomeFilme,str13,150);
	strncat (nomeFilme,str14,150);
	strncat (nomeFilme,str15,150);
	strncat (nomeFilme,str16,150);
	strncat (nomeFilme,str17,150);
	strncat (nomeFilme,str18,150);
	strncat (nomeFilme,str19,150);
	strncat (nomeFilme,str20,150);
	strncat (nomeFilme,str21,150);
	strncat (nomeFilme,str22,150);
	strncat (nomeFilme,str23,150);
	strncat (nomeFilme,str24,150);
	strncat (nomeFilme,str25,150);
	strncat (nomeFilme,str26,150);
	strncat (nomeFilme,str27,150);
	strncat (nomeFilme,str28,150);
	strncat (nomeFilme,str29,150);
	strncat (nomeFilme,str30,150);
	strncat (nomeFilme,str31,150);
	strncat (nomeFilme,str32,150);
	strncat (nomeFilme,str33,150);
	strncat (nomeFilme,str34,150);
		
	printf("%s",nomeFilme);
}
void lunar(){
	
	char nomeFilme[4000] = "";
	char str1[150]="              #########################################################################################\n";
	char str2[150]="              #########################| S.A. Poster - Indicação de Filmes |###########################\n";
	char str3[150]="              #########################################################################################\n";
	char str4[150]="              _________________________________________________________________________________________\n";
	char str5[150]="              ###################################| Nome do Filme |#####################################\n";
	char str6[150]="              #########################################################################################\n";
	char str7[150]="              |                                                                                       |\n";
	char str8[150]="              |                                     Lunar (Moon)                                      |\n";
	char str9[150]="              |_______________________________________________________________________________________|\n";
	char str10[150]="              ######################################| Sinopse |########################################\n";
	char str11[150]="              #########################################################################################\n";
	char str12[150]="              |                                                                                       |\n";
	char str13[150]="              |Sam Bell (Sam Rockwell) está perto de completar seu contrato de 3 anos com a Lunar     |\n";
	char str14[150]="              |Industries, que minera a fonte primária de energia da Terra no lado escuro da Lua.     |\n";
	char str15[150]="              |A única companhia de Sam é o vigilante computador da base chamado Gerty (Kevin Spacey).|\n";
	char str16[150]="              |_______________________________________________________________________________________|\n";
	char str17[150]="              ###########| Data de lançamento |#########|#########| Diretor & Roteirista(s) |##########\n";
	char str18[150]="              #########################################################################################\n";
	char str19[150]="              |                                         |                                             |\n";
	char str20[150]="              |           23 de Janeiro de 2009         |                Duncan Jones                 |\n";
	char str21[150]="              |       06 de Novembro de 2009 (Brasil)   |         Duncan Jones e Nathan Parker        |\n";
	char str22[150]="              |_________________________________________|_____________________________________________|\n";
	char str23[150]="              #########| Informações Adicionais |#######|#########| Gênero(s) Secundário(s) |##########\n";
	char str24[150]="              #########################################################################################\n";
	char str25[150]="              |                                         |                                             |\n";
	char str26[150]="              |        Duração - 97 min (1h37min)       |                   Mistério                  |\n";
	char str27[150]="              |      Classificação Etária - 12 anos     |                    Drama                    |\n";
	char str28[150]="              |_________________________________________|_____________________________________________|\n";
	char str29[150]="              ########| Nota no Rotten Tomatoes |#######|#########| Indicações e/ou Prêmios |##########\n";
	char str30[150]="              #########################################################################################\n";
	char str31[150]="              |                                         |                                             |\n";
	char str32[150]="              |        Nota dos Críticos - 7.5/10       |         Nenhum prêmio e/ou indicação        |\n";
	char str33[150]="              |         Nota da Audiência - 4/5         |                  importante                 |\n";
	char str34[150]="              |_________________________________________|_____________________________________________|\n";
	
	strncat (nomeFilme,str1,150);
	strncat (nomeFilme,str2,150);
	strncat (nomeFilme,str3,150);
	strncat (nomeFilme,str4,150);
	strncat (nomeFilme,str5,150);
	strncat (nomeFilme,str6,150);
	strncat (nomeFilme,str7,150);
	strncat (nomeFilme,str8,150);
	strncat (nomeFilme,str9,150);
	strncat (nomeFilme,str10,150);
	strncat (nomeFilme,str11,150);
	strncat (nomeFilme,str12,150);
	strncat (nomeFilme,str13,150);
	strncat (nomeFilme,str14,150);
	strncat (nomeFilme,str15,150);
	strncat (nomeFilme,str16,150);
	strncat (nomeFilme,str17,150);
	strncat (nomeFilme,str18,150);
	strncat (nomeFilme,str19,150);
	strncat (nomeFilme,str20,150);
	strncat (nomeFilme,str21,150);
	strncat (nomeFilme,str22,150);
	strncat (nomeFilme,str23,150);
	strncat (nomeFilme,str24,150);
	strncat (nomeFilme,str25,150);
	strncat (nomeFilme,str26,150);
	strncat (nomeFilme,str27,150);
	strncat (nomeFilme,str28,150);
	strncat (nomeFilme,str29,150);
	strncat (nomeFilme,str30,150);
	strncat (nomeFilme,str31,150);
	strncat (nomeFilme,str32,150);
	strncat (nomeFilme,str33,150);
	strncat (nomeFilme,str34,150);
		
	printf("%s",nomeFilme);
}
void apostolo(){
	
	char nomeFilme[4000] = "";
	char str1[150]="              #########################################################################################\n";
	char str2[150]="              #########################| S.A. Poster - Indicação de Filmes |###########################\n";
	char str3[150]="              #########################################################################################\n";
	char str4[150]="              _________________________________________________________________________________________\n";
	char str5[150]="              ###################################| Nome do Filme |#####################################\n";
	char str6[150]="              #########################################################################################\n";
	char str7[150]="              |                                                                                       |\n";
	char str8[150]="              |                                  Apóstolo (Apostle)                                   |\n";
	char str9[150]="              |_______________________________________________________________________________________|\n";
	char str10[150]="              ######################################| Sinopse |########################################\n";
	char str11[150]="              #########################################################################################\n";
	char str12[150]="              |                                                                                       |\n";
	char str13[150]="              | O ano é 1905. Thomas Richardson (Dan Stevens) viaja para uma ilha remota para resgatar|\n";
	char str14[150]="              | sua irmã depois que ela é sequestrada por um misterioso culto religioso.              |\n";
	char str15[150]="              |                                                                                       |\n";
	char str16[150]="              |_______________________________________________________________________________________|\n";
	char str17[150]="              ###########| Data de lançamento |#########|#########| Diretor & Roteirista(s) |##########\n";
	char str18[150]="              #########################################################################################\n";
	char str19[150]="              |                                         |                                             |\n";
	char str20[150]="              |          12 de Outubro de 2018          |                Gareth Evans                 |\n";
	char str21[150]="              |                                         |                                             |\n";
	char str22[150]="              |_________________________________________|_____________________________________________|\n";
	char str23[150]="              #########| Informações Adicionais |#######|#########| Gênero(s) Secundário(s) |##########\n";
	char str24[150]="              #########################################################################################\n";
	char str25[150]="              |                                         |                                             |\n";
	char str26[150]="              |        Duração - 130 min (2h10min)      |                   Terror                    |\n";
	char str27[150]="              |      Classificação Etária - 18 anos     |                    Drama                    |\n";
	char str28[150]="              |_________________________________________|_____________________________________________|\n";
	char str29[150]="              ########| Nota no Rotten Tomatoes |#######|#########| Indicações e/ou Prêmios |##########\n";
	char str30[150]="              #########################################################################################\n";
	char str31[150]="              |                                         |                                             |\n";
	char str32[150]="              |        Nota dos Críticos - 6.7/10       |         Nenhum prêmio e/ou indicação        |\n";
	char str33[150]="              |         Nota da Audiência - 3.3/5       |                  importante                 |\n";
	char str34[150]="              |_________________________________________|_____________________________________________|\n";
	
	strncat (nomeFilme,str1,150);
	strncat (nomeFilme,str2,150);
	strncat (nomeFilme,str3,150);
	strncat (nomeFilme,str4,150);
	strncat (nomeFilme,str5,150);
	strncat (nomeFilme,str6,150);
	strncat (nomeFilme,str7,150);
	strncat (nomeFilme,str8,150);
	strncat (nomeFilme,str9,150);
	strncat (nomeFilme,str10,150);
	strncat (nomeFilme,str11,150);
	strncat (nomeFilme,str12,150);
	strncat (nomeFilme,str13,150);
	strncat (nomeFilme,str14,150);
	strncat (nomeFilme,str15,150);
	strncat (nomeFilme,str16,150);
	strncat (nomeFilme,str17,150);
	strncat (nomeFilme,str18,150);
	strncat (nomeFilme,str19,150);
	strncat (nomeFilme,str20,150);
	strncat (nomeFilme,str21,150);
	strncat (nomeFilme,str22,150);
	strncat (nomeFilme,str23,150);
	strncat (nomeFilme,str24,150);
	strncat (nomeFilme,str25,150);
	strncat (nomeFilme,str26,150);
	strncat (nomeFilme,str27,150);
	strncat (nomeFilme,str28,150);
	strncat (nomeFilme,str29,150);
	strncat (nomeFilme,str30,150);
	strncat (nomeFilme,str31,150);
	strncat (nomeFilme,str32,150);
	strncat (nomeFilme,str33,150);
	strncat (nomeFilme,str34,150);
		
	printf("%s",nomeFilme);
}
void eragon(){
	
	char nomeFilme[4000] = "";
	char str1[150]="              #########################################################################################\n";
	char str2[150]="              #########################| S.A. Poster - Indicação de Filmes |###########################\n";
	char str3[150]="              #########################################################################################\n";
	char str4[150]="              _________________________________________________________________________________________\n";
	char str5[150]="              ###################################| Nome do Filme |#####################################\n";
	char str6[150]="              #########################################################################################\n";
	char str7[150]="              |                                                                                       |\n";
	char str8[150]="              |                                       Eragon                                          |\n";
	char str9[150]="              |_______________________________________________________________________________________|\n";
	char str10[150]="              ######################################| Sinopse |########################################\n";
	char str11[150]="              #########################################################################################\n";
	char str12[150]="              |                                                                                       |\n";
	char str13[150]="              | Menino que mora em uma fazenda encontra um ovo de dragão. A descoberta o leva a saber |\n";
	char str14[150]="              | que ele é um garoto predestinado a defender sua casa da ação de um rei malévolo.      |\n";
	char str15[150]="              |                                                                                       |\n";
	char str16[150]="              |_______________________________________________________________________________________|\n";
	char str17[150]="              ###########| Data de lançamento |#########|#########| Diretor & Roteirista(s) |##########\n";
	char str18[150]="              #########################################################################################\n";
	char str19[150]="              |                                         |                                             |\n";
	char str20[150]="              |          13 de Dezembro de 2006         |                Stefen Fangmeier             |\n";
	char str21[150]="              |          25 de Dezembro de 2006         |                 Peter Buchman               |\n";
	char str22[150]="              |_________________________________________|_____________________________________________|\n";
	char str23[150]="              #########| Informações Adicionais |#######|#########| Gênero(s) Secundário(s) |##########\n";
	char str24[150]="              #########################################################################################\n";
	char str25[150]="              |                                         |                                             |\n";
	char str26[150]="              |        Duração - 104 min (1h44min)      |                     Ação                    |\n";
	char str27[150]="              |      Classificação Etária - 10 anos     |                   Aventura                  |\n";
	char str28[150]="              |_________________________________________|_____________________________________________|\n";
	char str29[150]="              ########| Nota no Rotten Tomatoes |#######|#########| Indicações e/ou Prêmios |##########\n";
	char str30[150]="              #########################################################################################\n";
	char str31[150]="              |                                         |                                             |\n";
	char str32[150]="              |        Nota dos Críticos - 4.1/10       |         Nenhum prêmio e/ou indicação        |\n";
	char str33[150]="              |         Nota da Audiência - 3/5         |                  importante                 |\n";
	char str34[150]="              |_________________________________________|_____________________________________________|\n";
	
	strncat (nomeFilme,str1,150);
	strncat (nomeFilme,str2,150);
	strncat (nomeFilme,str3,150);
	strncat (nomeFilme,str4,150);
	strncat (nomeFilme,str5,150);
	strncat (nomeFilme,str6,150);
	strncat (nomeFilme,str7,150);
	strncat (nomeFilme,str8,150);
	strncat (nomeFilme,str9,150);
	strncat (nomeFilme,str10,150);
	strncat (nomeFilme,str11,150);
	strncat (nomeFilme,str12,150);
	strncat (nomeFilme,str13,150);
	strncat (nomeFilme,str14,150);
	strncat (nomeFilme,str15,150);
	strncat (nomeFilme,str16,150);
	strncat (nomeFilme,str17,150);
	strncat (nomeFilme,str18,150);
	strncat (nomeFilme,str19,150);
	strncat (nomeFilme,str20,150);
	strncat (nomeFilme,str21,150);
	strncat (nomeFilme,str22,150);
	strncat (nomeFilme,str23,150);
	strncat (nomeFilme,str24,150);
	strncat (nomeFilme,str25,150);
	strncat (nomeFilme,str26,150);
	strncat (nomeFilme,str27,150);
	strncat (nomeFilme,str28,150);
	strncat (nomeFilme,str29,150);
	strncat (nomeFilme,str30,150);
	strncat (nomeFilme,str31,150);
	strncat (nomeFilme,str32,150);
	strncat (nomeFilme,str33,150);
	strncat (nomeFilme,str34,150);
		
	printf("%s",nomeFilme);
}
