Algoritmo "Exercício 1 - Estrutura Condicional"
// Disciplina  :
// Professor(a):  
// Descrição   :
// Autor(a)    :
// Data atual  :
Var
// Seção de Declarações das variáveis 
   n: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Informe um número: ")
   leia(n)
   se n>20 entao
      escreval("O número informado é maior que 20")
   fimse
Fimalgoritmo