algoritmo "Exercício 17 - Parte 2"
// Função :
// Autor :
// Data : 18/10/2018
// Seção de Declarações 
var
   a,b,c: real
inicio
// Seção de Comandos
   escreval("Informe valores para:")
                     escreva("A: ")
                     leia(a)
                     escreva("B: ")
                     leia(b)
   limpatela
   se a=b entao
   c<-a+b
         escreval(c)
   senao
   c<-a*b
        escreval(c)
   fimse
fimalgoritmo
