algoritmo "Exercício 11 - Parte 2"
// Função :
// Autor :
// Data : 18/10/2018
// Seção de Declarações 
var
   h,b,area: real
inicio
// Seção de Comandos
   escreval("Informe as medidas do terreno:")
                     escreva("Altura: ")
                     leia(h)
                     escreva("Base: ")
                     leia(b)
   limpatela
   area<-b*h
   se area>100 entao
      escreval("Terreno grande")
   senao
        escreval("Terreno pequeno")
   fimse
   

fimalgoritmo
