algoritmo "Exercício 1 - Vetor"
// Disciplina: [Linguagem e Lógica de Programação]
// Professor(a): Antonio Carlos Nicolodi
// Função :
// Autor :
// Data : 31/10/2018
// Seção de Declarações
var
   a: vetor[0..4] de inteiro
   i,num: inteiro
inicio
   // Seção de Comandos
   para i de 0 ate 4 faca
      escreval("Informe um valor:")
      leia(a[i])
      limpatela
   fimpara
   para i de 0 ate 4 faca
      escreval("Números informados anteriormente: ",a[i])
   fimpara

fimalgoritmo
