algoritmo "Exercício 1"
// Função :
// Autor : Gabriel Sousa
// Data : 10/10/2018
// Seção de Declarações 
var
   base,altura: inteiro

inicio
// Seção de Comandos
   escreval("Informe a base do retângulo: ")
   leia(base)
   escreval("Informe a altura do retângulo: ")
   leia(altura)
   escreval("A área do retângulo é: ", base*altura)
   escreval("O perímetro do retângulo é: ",base+base+altura+altura)
fimalgoritmo
