algoritmo "Exercício 2 - Parte 2"
// Função :
// Autor :
// Data : 17/10/2018
// Seção de Declarações 
var
   n: real
inicio
// Seção de Comandos
   escreval("Informe um número: ")
   leia(n)
   se n=0 entao
      escreval("O valor digitado foi zero.")
   fimse
   se n>0 entao
      escreval("O número informado é positivo.")
   senao
   se n<0 entao
      escreval("O número informado é negativo.")
   fimse
   fimse
fimalgoritmo

