algoritmo "Exercício 6 - Parte 2"
// Função :
// Autor :
// Data : 17/10/2018
// Seção de Declarações 
var
   n: inteiro
   r: real
inicio
// Seção de Comandos
   escreval("Informe um número INTEIRO, POSITIVO e MAIOR QUE ZERO!!!")
   leia(n)
   limpatela
   r<-n%2
   se n<0 entao
      escreva ("Número inválido.")
   senao
   se r=0 entao
      escreval(n," é um número par.")
   senao
        escreval(n," é um número ímpar.")
   fimse
   fimse

   
   
fimalgoritmo
