algoritmo "Exercício 1 - Matriz"
// Função :
// Autor :
// Data : 06/11/2018
// Seção de Declarações
var
i,j: inteiro
m: vetor [0..1,0..3] de inteiro
inicio
// Seção de Comandos
para i de 0 ate 1 faca
   para j de 0 ate 3 faca
      escreva("Informe um número: ")
      leia(m[i,j])
   fimpara
fimpara
limpatela
para i de 0 ate 1 faca
   para j de 0 ate 3 faca
      escreval("Os números digitados foram: ",m[i,j])
   fimpara
fimpara
fimalgoritmo
